import { describe, it, expect, beforeEach } from 'vitest';
import type { OutputAdapter, VaultEntry } from '../adapters/interface';
import type { ObsyncConfig } from '../config/types';
import type { StateFile } from '../state/types';
import { generateIndexPages } from './index-page';

// MockAdapter captures writeEntry calls keyed by destinationPath
class MockAdapter implements OutputAdapter {
  readonly entries = new Map<string, VaultEntry>();

  async writeEntry(entry: VaultEntry): Promise<void> {
    this.entries.set(entry.destinationPath, entry);
  }

  async deleteEntry(destinationPath: string): Promise<void> {
    this.entries.delete(destinationPath);
  }
}

// Minimal valid config builder
function makeConfig(
  sources: Array<{
    name: string;
    category: string;
    labels: string[];
    path?: string;
  }>,
  vaultPath = '/vault',
): ObsyncConfig {
  return {
    vault: { path: vaultPath },
    sources: sources.map((s) => ({
      name: s.name,
      path: s.path ?? `/sources/${s.name}`,
      category: s.category,
      scan: 'scattered' as const,
      ai_summary: false,
      ignore: [],
      ai_ignore: [],
      labels: s.labels,
    })),
    ignore: [],
  };
}

function makeState(
  files: Record<
    string,
    {
      sourceName: string;
      destinationPath: string;
      syncedAt: string;
      tags?: string[];
    }
  >,
): StateFile {
  const stateFiles: StateFile['files'] = {};
  for (const [key, val] of Object.entries(files)) {
    stateFiles[key] = {
      hash: 'abc123',
      gitRef: null,
      syncedAt: val.syncedAt,
      sourceName: val.sourceName,
      destinationPath: val.destinationPath,
      ...(val.tags !== undefined ? { tags: val.tags } : {}),
    };
  }
  return {
    version: '1',
    updatedAt: new Date().toISOString(),
    files: stateFiles,
  };
}

describe('generateIndexPages', () => {
  let adapter: MockAdapter;

  beforeEach(() => {
    adapter = new MockAdapter();
  });

  it('writes zero entries when no sources have labels', async () => {
    const config = makeConfig([{ name: 'infra', category: 'Infrastructure', labels: [] }]);
    const state = makeState({});
    await generateIndexPages(config, state, adapter);
    expect(adapter.entries.size).toBe(0);
  });

  it('writes correct file path for disaster-recovery label', async () => {
    const config = makeConfig([
      { name: 'infra', category: 'Infrastructure', labels: ['disaster-recovery'] },
    ]);
    const state = makeState({});
    await generateIndexPages(config, state, adapter);
    expect(adapter.entries.has('/vault/_index/Disaster-Recovery.md')).toBe(true);
  });

  it('writes correct frontmatter for label', async () => {
    const config = makeConfig([
      { name: 'infra', category: 'Infrastructure', labels: ['disaster-recovery'] },
    ]);
    const state = makeState({});
    await generateIndexPages(config, state, adapter);
    const entry = adapter.entries.get('/vault/_index/Disaster-Recovery.md')!;
    expect(entry.mergedFrontmatter['tags']).toEqual(['disaster-recovery']);
    expect(entry.mergedFrontmatter['obsync_generated_by']).toBe('obsync');
    expect(typeof entry.mergedFrontmatter['obsync_updated_at']).toBe('string');
    // Verify it's a valid ISO string
    const updatedAt = entry.mergedFrontmatter['obsync_updated_at'] as string;
    expect(() => new Date(updatedAt).toISOString()).not.toThrow();
  });

  it('H1 heading uses label display name with spaces', async () => {
    const config = makeConfig([
      { name: 'infra', category: 'Infrastructure', labels: ['disaster-recovery'] },
    ]);
    const state = makeState({});
    await generateIndexPages(config, state, adapter);
    const entry = adapter.entries.get('/vault/_index/Disaster-Recovery.md')!;
    expect(entry.body).toContain('# Disaster Recovery');
  });

  it('includes attribution blockquote', async () => {
    const config = makeConfig([
      { name: 'infra', category: 'Infrastructure', labels: ['runbook'] },
    ]);
    const state = makeState({});
    await generateIndexPages(config, state, adapter);
    const entry = adapter.entries.get('/vault/_index/Runbook.md')!;
    expect(entry.body).toContain('> Generated by obsync. Updated on every sync run.');
  });

  it('renders empty-state body when no files match label', async () => {
    const config = makeConfig([
      { name: 'infra', category: 'Infrastructure', labels: ['disaster-recovery'] },
    ]);
    const state = makeState({});
    await generateIndexPages(config, state, adapter);
    const entry = adapter.entries.get('/vault/_index/Disaster-Recovery.md')!;
    expect(entry.body).toContain('*No files are currently tagged with this label.*');
    // Page still written even when empty
    expect(adapter.entries.has('/vault/_index/Disaster-Recovery.md')).toBe(true);
  });

  it('single label single source single file: correct H3 and entry format', async () => {
    const config = makeConfig([
      { name: 'thornode', category: 'Infrastructure', labels: ['runbook'] },
    ]);
    const state = makeState({
      'thornode/runbook.md': {
        sourceName: 'thornode',
        destinationPath: '/vault/Infrastructure/thornode/runbook.md',
        syncedAt: '2026-06-09T00:00:00.000Z',
      },
    });
    await generateIndexPages(config, state, adapter);
    const entry = adapter.entries.get('/vault/_index/Runbook.md')!;
    expect(entry.body).toContain('### thornode');
    expect(entry.body).toContain('[[Infrastructure/thornode/runbook|runbook]]');
    expect(entry.body).toContain('— thornode (synced 2026-06-09)');
  });

  it('wikilink target has no .md extension and no leading slash', async () => {
    const config = makeConfig([
      { name: 'infra', category: 'Infrastructure', labels: ['runbook'] },
    ]);
    const state = makeState({
      'infra/guide.md': {
        sourceName: 'infra',
        destinationPath: '/vault/Infrastructure/infra/guide.md',
        syncedAt: '2026-06-09T00:00:00.000Z',
      },
    });
    await generateIndexPages(config, state, adapter);
    const entry = adapter.entries.get('/vault/_index/Runbook.md')!;
    // Must not contain .md in wikilink target
    expect(entry.body).toMatch(/\[\[Infrastructure\/infra\/guide\|/);
    // Must not start with slash
    expect(entry.body).not.toMatch(/\[\[\//);
  });

  it('multi-file same source: entries sorted alphabetically by filename', async () => {
    const config = makeConfig([
      { name: 'infra', category: 'Infrastructure', labels: ['runbook'] },
    ]);
    const state = makeState({
      'infra/zebra.md': {
        sourceName: 'infra',
        destinationPath: '/vault/Infrastructure/infra/zebra.md',
        syncedAt: '2026-06-09T00:00:00.000Z',
      },
      'infra/alpha.md': {
        sourceName: 'infra',
        destinationPath: '/vault/Infrastructure/infra/alpha.md',
        syncedAt: '2026-06-09T00:00:00.000Z',
      },
    });
    await generateIndexPages(config, state, adapter);
    const entry = adapter.entries.get('/vault/_index/Runbook.md')!;
    const alphaPos = entry.body.indexOf('alpha');
    const zebraPos = entry.body.indexOf('zebra');
    expect(alphaPos).toBeLessThan(zebraPos);
  });

  it('two sources with same label: both appear as separate H3 sections sorted alphabetically', async () => {
    const config = makeConfig([
      { name: 'beta-source', category: 'Infrastructure', labels: ['runbook'] },
      { name: 'alpha-source', category: 'Infrastructure', labels: ['runbook'] },
    ]);
    const state = makeState({
      'beta-source/guide.md': {
        sourceName: 'beta-source',
        destinationPath: '/vault/Infrastructure/beta-source/guide.md',
        syncedAt: '2026-06-09T00:00:00.000Z',
      },
      'alpha-source/guide.md': {
        sourceName: 'alpha-source',
        destinationPath: '/vault/Infrastructure/alpha-source/guide.md',
        syncedAt: '2026-06-09T00:00:00.000Z',
      },
    });
    await generateIndexPages(config, state, adapter);
    const entry = adapter.entries.get('/vault/_index/Runbook.md')!;
    const alphaPos = entry.body.indexOf('### alpha-source');
    const betaPos = entry.body.indexOf('### beta-source');
    expect(alphaPos).toBeGreaterThan(-1);
    expect(betaPos).toBeGreaterThan(-1);
    expect(alphaPos).toBeLessThan(betaPos);
  });

  it('file with two labels: appears in both index pages', async () => {
    const config = makeConfig([
      { name: 'infra', category: 'Infrastructure', labels: ['runbook', 'disaster-recovery'] },
    ]);
    const state = makeState({
      'infra/dr.md': {
        sourceName: 'infra',
        destinationPath: '/vault/Infrastructure/infra/dr.md',
        syncedAt: '2026-06-09T00:00:00.000Z',
      },
    });
    await generateIndexPages(config, state, adapter);
    expect(adapter.entries.has('/vault/_index/Runbook.md')).toBe(true);
    expect(adapter.entries.has('/vault/_index/Disaster-Recovery.md')).toBe(true);
    const runbookEntry = adapter.entries.get('/vault/_index/Runbook.md')!;
    const drEntry = adapter.entries.get('/vault/_index/Disaster-Recovery.md')!;
    expect(runbookEntry.body).toContain('dr');
    expect(drEntry.body).toContain('dr');
  });

  it('entry date derived from syncedAt local date', async () => {
    // Use a known UTC time that maps to a specific local date
    // We test by verifying the date format is YYYY-MM-DD
    const config = makeConfig([
      { name: 'infra', category: 'Infrastructure', labels: ['runbook'] },
    ]);
    const state = makeState({
      'infra/guide.md': {
        sourceName: 'infra',
        destinationPath: '/vault/Infrastructure/infra/guide.md',
        syncedAt: '2026-06-09T12:00:00.000Z',
      },
    });
    await generateIndexPages(config, state, adapter);
    const entry = adapter.entries.get('/vault/_index/Runbook.md')!;
    // Entry must contain a date in YYYY-MM-DD format
    expect(entry.body).toMatch(/synced \d{4}-\d{2}-\d{2}/);
  });

  it('labelToFilename: infrastructure becomes Infrastructure', async () => {
    const config = makeConfig([
      { name: 'infra', category: 'Infrastructure', labels: ['infrastructure'] },
    ]);
    const state = makeState({});
    await generateIndexPages(config, state, adapter);
    expect(adapter.entries.has('/vault/_index/Infrastructure.md')).toBe(true);
  });

  it('labelToFilename: disaster-recovery becomes Disaster-Recovery', async () => {
    const config = makeConfig([
      { name: 'infra', category: 'Infrastructure', labels: ['disaster-recovery'] },
    ]);
    const state = makeState({});
    await generateIndexPages(config, state, adapter);
    expect(adapter.entries.has('/vault/_index/Disaster-Recovery.md')).toBe(true);
  });

  it('config label + file tags: produces both pages, file appears once in label page (no duplicate from union)', async () => {
    const config = makeConfig([
      { name: 'infra', category: 'Infrastructure', labels: ['runbook'] },
    ]);
    const state = makeState({
      'infra/dr.md': {
        sourceName: 'infra',
        destinationPath: '/vault/Infrastructure/infra/dr.md',
        syncedAt: '2026-06-09T00:00:00.000Z',
        tags: ['runbook', 'dr'],
      },
    });
    await generateIndexPages(config, state, adapter);
    expect(adapter.entries.has('/vault/_index/Runbook.md')).toBe(true);
    expect(adapter.entries.has('/vault/_index/Dr.md')).toBe(true);

    const runbookEntry = adapter.entries.get('/vault/_index/Runbook.md')!;
    // The file must appear only once in the Runbook page despite being in both
    // sourceConfig.labels (['runbook']) and fileEntry.tags (['runbook', 'dr']).
    expect(runbookEntry.body.match(/\[\[Infrastructure\/infra\/dr\|/g)?.length).toBe(1);
  });

  it('empty config labels but file tags present: still produces an index page (no early-return)', async () => {
    const config = makeConfig([{ name: 'notes', category: 'Personal', labels: [] }]);
    const state = makeState({
      'notes/today.md': {
        sourceName: 'notes',
        destinationPath: '/vault/Personal/notes/today.md',
        syncedAt: '2026-06-09T00:00:00.000Z',
        tags: ['notes'],
      },
    });
    await generateIndexPages(config, state, adapter);
    expect(adapter.entries.has('/vault/_index/Notes.md')).toBe(true);
    const entry = adapter.entries.get('/vault/_index/Notes.md')!;
    expect(entry.body).toContain('[[Personal/notes/today|');
  });

  it('zero config labels and zero file tags: writes nothing and returns 0', async () => {
    const config = makeConfig([{ name: 'notes', category: 'Personal', labels: [] }]);
    const state = makeState({
      'notes/today.md': {
        sourceName: 'notes',
        destinationPath: '/vault/Personal/notes/today.md',
        syncedAt: '2026-06-09T00:00:00.000Z',
      },
    });
    const count = await generateIndexPages(config, state, adapter);
    expect(adapter.entries.size).toBe(0);
    expect(count).toBe(0);
  });

  it('returns the count of distinct labels generated', async () => {
    const config = makeConfig([
      { name: 'infra', category: 'Infrastructure', labels: ['runbook'] },
    ]);
    const state = makeState({
      'infra/dr.md': {
        sourceName: 'infra',
        destinationPath: '/vault/Infrastructure/infra/dr.md',
        syncedAt: '2026-06-09T00:00:00.000Z',
        tags: ['runbook', 'dr'],
      },
    });
    const count = await generateIndexPages(config, state, adapter);
    // distinct labels: 'runbook' (config) ∪ 'runbook', 'dr' (file tags) = {runbook, dr}
    expect(count).toBe(2);
    expect(adapter.entries.size).toBe(2);
  });
});
