/**
 * generateIndexPages — produce _index/{Label-Name}.md files for each configured label.
 *
 * For each unique label in config.sources[].labels, writes one page listing all vault
 * files tagged with that label. Pages are written through OutputAdapter.writeEntry()
 * so atomic writes and path confinement are inherited automatically.
 *
 * Requirements: CAT-03, CAT-04, CAT-05
 */

import * as path from 'path';
import type { ObsyncConfig } from '../config/types';
import type { StateFile } from '../state/types';
import type { OutputAdapter, VaultEntry } from '../adapters/interface';

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * labelToFilename — converts a label to its Title-Cased-Hyphenated filename segment.
 * Examples: 'disaster-recovery' → 'Disaster-Recovery', 'infrastructure' → 'Infrastructure'
 */
function labelToFilename(label: string): string {
  return label
    .split(/[-\s]+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('-');
}

/**
 * labelToDisplayName — converts a label to its Title Cased display name with spaces.
 * Examples: 'disaster-recovery' → 'Disaster Recovery', 'infrastructure' → 'Infrastructure'
 */
function labelToDisplayName(label: string): string {
  return label
    .split(/[-\s]+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

/**
 * toWikilink — produces a vault-relative wikilink target and display name from an
 * absolute destination path.
 *
 * Target: vault-relative, no leading slash, no .md extension.
 * Display: filename without extension.
 */
function toWikilink(
  destPath: string,
  vaultRoot: string,
): { target: string; display: string } {
  const rel = path
    .relative(vaultRoot, destPath)
    .replace(/\.md$/, '')
    .replace(/\\/g, '/');
  const display = path.basename(destPath, '.md');
  return { target: rel, display };
}

/**
 * syncDateFromISO — parses an ISO 8601 string and returns a local YYYY-MM-DD date string.
 * Uses local date methods (getFullYear, getMonth, getDate) per UI-SPEC §6.1.
 */
function syncDateFromISO(isoString: string): string {
  const d = new Date(isoString);
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

// ---------------------------------------------------------------------------
// Body builder
// ---------------------------------------------------------------------------

interface IndexEntry {
  sourceName: string;
  destPath: string;
  syncedAt: string;
}

/**
 * buildIndexBody — constructs the markdown body for a label index page.
 *
 * Structure (UI-SPEC §1.3):
 * - Attribution blockquote
 * - If no entries: empty-state copy (§1.7)
 * - Otherwise: H3 per source (alphabetical), entries within source (alphabetical by filename)
 */
function buildIndexBody(
  label: string,
  entries: readonly IndexEntry[],
  vaultRoot: string,
): string {
  const displayName = labelToDisplayName(label);
  const h1 = `# ${displayName}\n`;
  const attribution = '> Generated by obsync. Updated on every sync run.\n';

  if (entries.length === 0) {
    return (
      h1 +
      '\n' +
      attribution +
      '\n' +
      '*No files are currently tagged with this label.*\n'
    );
  }

  // Group by sourceName.
  // Map insertion order is irrelevant — sortedSourceNames re-sorts below.
  const grouped = new Map<string, IndexEntry[]>();
  for (const entry of entries) {
    const group = grouped.get(entry.sourceName) ?? [];
    group.push(entry);
    grouped.set(entry.sourceName, group);
  }

  // Sort source group keys alphabetically
  const sortedSourceNames = [...grouped.keys()].sort();

  let body = h1 + '\n' + attribution + '\n';

  for (const sourceName of sortedSourceNames) {
    const sourceEntries = grouped.get(sourceName)!;

    // Sort entries within the group alphabetically by display filename
    const sortedEntries = [...sourceEntries].sort((a, b) => {
      const aDisplay = path.basename(a.destPath, '.md');
      const bDisplay = path.basename(b.destPath, '.md');
      return aDisplay.localeCompare(bDisplay);
    });

    body += `### ${sourceName}\n\n`;

    for (const entry of sortedEntries) {
      const { target, display } = toWikilink(entry.destPath, vaultRoot);
      const syncDate = syncDateFromISO(entry.syncedAt);
      body += `- [[${target}|${display}]] — ${sourceName} (synced ${syncDate})\n`;
    }

    body += '\n';
  }

  return body;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * generateIndexPages — writes one _index/{Label-Name}.md page per unique label
 * across all configured sources, plus every distinct per-file tag (D-67).
 *
 * Algorithm:
 * 1. Collect all unique labels: union of config.sources[].labels and every
 *    fileEntry.tags across state.files (frontmatter tags + inline #hashtag
 *    extraction, D-67/D-68).
 * 2. Build label → entries mapping from state.files, where each file's label
 *    set is the deduplicated union of its source's config labels and its own tags.
 * 3. For each label, build the page body and write via adapter.writeEntry()
 *
 * Files with multiple labels appear in each relevant index page (CAT-05), now
 * extended to inline-tag-derived pages as well. Pages with no matching files
 * still write the empty-state body (UI-SPEC §1.7).
 *
 * @returns The number of distinct index pages generated (D-69).
 */
export async function generateIndexPages(
  config: ObsyncConfig,
  state: StateFile,
  adapter: OutputAdapter,
): Promise<number> {
  const vaultRoot = config.vault.path;

  // Step 1: Collect all unique labels across all sources, plus per-file tags.
  const allLabels = new Set<string>();
  for (const source of config.sources) {
    for (const label of source.labels) {
      allLabels.add(label);
    }
  }
  for (const fileEntry of Object.values(state.files)) {
    for (const tag of fileEntry.tags ?? []) {
      allLabels.add(tag);
    }
  }

  // D-69: only return early when the unioned set (config labels + file tags) is
  // empty — a source with empty config labels but files carrying tags must still
  // produce pages.
  if (allLabels.size === 0) {
    return 0;
  }

  // Step 2: Build label → entries mapping using state.files
  const labelMap = new Map<string, IndexEntry[]>();
  for (const label of allLabels) {
    labelMap.set(label, []);
  }

  for (const [, fileEntry] of Object.entries(state.files)) {
    const sourceConfig = config.sources.find((s) => s.name === fileEntry.sourceName);
    const sourceLabels = sourceConfig?.labels ?? [];
    const fileTags = fileEntry.tags ?? [];

    // Deduplicated union of this file's config-label set and its own tags (D-67).
    const fileLabels = [...sourceLabels, ...fileTags.filter((t) => !sourceLabels.includes(t))];

    for (const label of fileLabels) {
      const entries = labelMap.get(label);
      if (entries !== undefined) {
        entries.push({
          sourceName: fileEntry.sourceName,
          destPath: fileEntry.destinationPath,
          syncedAt: fileEntry.syncedAt,
        });
      }
    }
  }

  // Step 3: Write one page per label
  // Single timestamp for this run, reused for both obsync_updated_at and
  // metadata.syncedAt so the two fields can never diverge across iterations
  // (IN-02).
  const generatedAt = new Date().toISOString();

  for (const [label, entries] of labelMap) {
    const body = buildIndexBody(label, entries, vaultRoot);

    const frontmatter: Record<string, unknown> = {
      tags: [label],
      obsync_generated_by: 'obsync',
      obsync_updated_at: generatedAt,
    };

    const vaultEntry: VaultEntry = {
      destinationPath: `${vaultRoot}/_index/${labelToFilename(label)}.md`,
      mergedFrontmatter: frontmatter,
      body,
      metadata: {
        sourceFile: '',
        hash: '',
        gitRef: null,
        syncedAt: generatedAt,
      },
    };

    await adapter.writeEntry(vaultEntry);
  }

  return labelMap.size;
}
